### ISSUE TITLE
JMH Benchmark - Setup

### ISSUE THREAD

**Issue by sergiotudela** [emstlk/nacl4s#3]
Hi,

Many thanks to write this library in Scala, it's very helpful! At least in my case because it's a good chance to change my calls to libsodium via JNDI.

I'm adding an initial phase of JMH to run performance tests, so can I do a pull request over this issue?

**Comment by emstlk** [comment]
Of course, welcome to benchmarks. I'll try to review it today

**Comment by sergiotudela** [comment]
Hi,

As you can see, the tests are very simple and are not covering all cases. So the changes in the PR are just a setup or something like that, you know in order to start on implementing more cases.
